### ISSUE TITLE
Can't run on Android 6.0

### ISSUE THREAD

**Issue by neerup** [appcelerator-modules/ti.paint#12]
Can't run on Android 6.0 with SDK 5.1 because of  text relocations.
This is the 64Bit problem with IOS modules all over again... the SDK is upgraded but the modules is not..
This renders SDK 5.1 GA useless if You use this module... 
Sorry for the language, but this is frustrating...

**Comment by ashcoding** [comment]
@neerup You can follow https://jira.appcelerator.org/browse/MOD-2167. There's an attached binary in the ticket that contains `ti.paint-android-2.0.3.zip`if you need to use it urgently. I'm in the process of putting it in the github release page of this module.

**Comment by ashcoding** [comment]
Release located here: https://github.com/appcelerator-modules/ti.paint/releases/tag/android-2.0.3

Closing issue.
